server:
  port: 6700
  servlet:
    context-path: /auth

spring:
  datasource:
    url: jdbc:mysql://localhost:3302/internet_banking
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: gDzVa7PsnEfArGYW35djCg1jVkcRn1Nu
    realm: internet-banking-api-client
    serverUrl: http://localhost:8081
# ugoukkdbwclrxmrt mail password
